V16
KuryKat/HaremHotel-BR pull request #1
Opened 2022-11-28 22:30 UTC by liandroam

# Modelo de Pull Request

O modelo a seguir deve ser utilizado ao criar um Pull Request.

## Descrição

Inclua um resumo da alteração e qual Issue foi corrigido. Inclua também motivação e contexto relevantes. Liste todas as possíveis dependências necessárias para essa alteração.

Corrige # (issue)

## Tipo de mudança

Exclua as opções que não são relevantes.

- [ X] Correção de Tradução
- [ X] Nova Tradução

## Como isso foi testado?

Descreva os testes que você executou para verificar suas alterações. Forneça instruções para que possamos reproduzir. Liste também todos os detalhes relevantes para sua configuração de testes.

- [ ] Teste A
- [ ] Teste B

**Configurações**:

- Versão do RenPy (SDK):
- Versão do Python:
- Ferramentas Utilizadas:

## Checklist

- [ X] Minha tradução segue as diretrizes de qualidade deste projeto.
- [ X] Realizei uma autorrevisão da minha própria tradução.
- [ ] Minhas alterações não geram novos erros.

Suas alterações não serão aceitas caso algumas dessas verificações não sejam cumpridas.

2022-11-29 02:27 UTC, KuryKat commented on scripts/animations_and_flags.rpy
> -translate pt_br strings:
@liandroam Por favor altere pra que todos seus arquivos utilizem o padrão "pt_br" que está default em vez desse

2022-11-29 03:37 UTC, LuckShiba requested changes
Sugestão de algumas mudanças

2022-11-29 03:37 UTC, LuckShiba commented on scripts/computer.rpy
> +    r "Um grande obrigado aos meus apioadores!"
apoiadores

2022-11-29 03:37 UTC, LuckShiba commented on scripts/computer.rpy
> +    "A imagem que você selecionou para o wallpaper do pc não está nos arquivos do jogo, pode ser que acabou sendo corrompida ou tenha sido modificada."
"pode ser que acabou sendo corrompida ou tenha sido modificada." não está no texto original

2022-11-29 03:37 UTC, LuckShiba commented on scripts/computer.rpy
> +    new "Ajude o jogo à continuar"
"Apoie o jogo" seria melhor, pois "ajude" leva a uma idéia de fazer parte ao contrário de apoiar.

2022-11-29 03:37 UTC, LuckShiba commented on scripts/computer.rpy
> +    new "Ajude o jogo à continuar"
Remover o "à continuar", além de não estar no original, a crase está incorreta

2022-11-29 03:37 UTC, LuckShiba commented on scripts/dreamscape.rpy
> +    m "Ela ficou tão animada quando [name] propôs... Talvez ela tenha ficado com os pés frios?"
"propôs" -> "a pediu em casamento"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/dreamscape.rpy
> +    m "Ash! Onde você esteve? Você está tão atrasada! [name] está esperando à um tempão!"
"faz um tempão"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/dreamscape.rpy
> +    e "Vocês dois se comprometem a compartilhar suas vidas abrindo um com o outro e falar a verdade em amor?"
"se abrindo", não "abrindo".

2022-11-29 03:37 UTC, LuckShiba commented on scripts/dreamscape.rpy
> +    e "Vocês dois se comprometem a compartilhar suas vidas abrindo um com o outro e falar a verdade em amor?"
"e a falar a verdade"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/dreamscape.rpy
> +    a "Aceito."
"Prometo."

2022-11-29 03:37 UTC, LuckShiba commented on scripts/dreamscape.rpy
> +    c "Aceito."
"Prometo."

2022-11-29 03:37 UTC, LuckShiba commented on scripts/dreamscape.rpy
> +    a "Aceito."
"Sim."

2022-11-29 03:37 UTC, LuckShiba commented on scripts/dreamscape.rpy
> +    c "Aceito."
"Sim."

2022-11-29 03:37 UTC, LuckShiba commented on scripts/dreamscape.rpy
> +    a "Eu não posso acreditar que está realmente acontecendo!"
"Eu não posso acreditar que **isso** está realmente acontecendo!"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/wallpaper.rpy
> +    new "Gostaria de definir esta imagem como seu wallpaper?"
"papel de parede"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/store_sextoys.rpy
> +    "Você não tem dinheiro suficiente para isso"
"Eu não tenho", não "Você não tem"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/store_sextoys.rpy
> +    "Você não tem dinheiro suficiente para isso"
"Eu não tenho", não "Você não tem"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/store_sextoys.rpy
> +    "Você não tem dinheiro suficiente para isso"
"Eu não tenho", não "Você não tem"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/store_sextoys.rpy
> +    "Você não tem dinheiro suficiente para isso"
"Eu não tenho", não "Você não tem"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/store_sextoys.rpy
> +    "Você não tem dinheiro suficiente para isso"
"Eu não tenho", não "Você não tem"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/store_sextoys.rpy
> +    "Você não tem dinheiro suficiente para isso"
"Eu não tenho", não "Você não tem"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/store_sextoys.rpy
> +    "Você não tem dinheiro suficiente para isso"
"Eu não tenho", não "Você não tem"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/store_sextoys.rpy
> +    "Você não tem dinheiro suficiente para isso"
"Eu não tenho", não "Você não tem"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/store_sextoys.rpy
> +    "Você não tem dinheiro suficiente para isso"
"Eu não tenho", não "Você não tem"

2022-11-29 03:37 UTC, LuckShiba commented on scripts/gallery.rpy
> +    new "Autumn"
"Outono"

2022-11-29 03:51 UTC, KuryKat commented on scripts/gallery.rpy
> +    new "Autumn"
Desconsiderado pois é um nome, entendível pois você nunca jogou o jogo hehe, valeu pela ajuda Shiba ❤

2022-11-29 03:52 UTC, KuryKat commented on scripts/computer.rpy
> +    r "Um grande obrigado aos meus apioadores!"
Fixed!

2022-11-29 03:57 UTC, KuryKat commented
Arquivos Totalmente Revisados

- scripts/
    - [X] animations_and_flags.rpy (by @LuckShiba)
    - computer.rpy
    - dreamscape.rpy
    - [X] gallery.rpy (by @LuckShiba)
    - input_code.rpy
    - main.rpy
    - screens.rpy
    - spycams.rpy
    - store_elves.rpy
    - store_gifts.rpy
    - store_other.rpy
    - store_outfits.rpy
    - [X] store_sextoys.rpy (by @LuckShiba)
    - [X] sylmap.rpy (by @LuckShiba)
    - [X] wallpaper.rpy (by @LuckShiba)

(Ainda em aguardo pelas correções necessárias por parte do tradutor)

2022-12-11 17:31 UTC, KuryKat commented
Reabrindo pois só precisava alterar o branch pra onde o PR vai ser mergeado

2025-07-19 13:31 UTC, closed without merging